/**
 * Generates dist/tokens.css (CSS custom properties) and dist/_tokens.scss
 * from the single TS source. Run as part of `build`.
 *
 * CSS var naming: --bion-<group>-<key>  (camelCase key → kebab-case)
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { tokens } from '../src/index.ts';

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const flat = [];
for (const [group, entries] of Object.entries(tokens)) {
  for (const [key, value] of Object.entries(entries)) {
    flat.push([`--bion-${kebab(group)}-${kebab(key)}`, value]);
  }
}

const cssBody = flat.map(([k, v]) => `  ${k}: ${v};`).join('\n');
const css = `/* Generated by @bion-mfe-ui/tokens — do not edit by hand. */\n:root {\n${cssBody}\n}\n`;

const scssBody = flat
  .map(([k, v]) => `  "${k.replace('--bion-', '')}": ${v},`)
  .join('\n');
const scss = `// Generated by @bion-mfe-ui/tokens — do not edit by hand.\n$bion-tokens: (\n${scssBody}\n);\n`;

await mkdir(new URL('../dist/', import.meta.url), { recursive: true });
await writeFile(new URL('../dist/tokens.css', import.meta.url), css);
await writeFile(new URL('../dist/_tokens.scss', import.meta.url), scss);

console.log(`tokens: wrote ${flat.length} variables → dist/tokens.css, dist/_tokens.scss`);
